// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlnWz6sTkKvR0je40n7IC52O0_fCB5XAM',
    appId: '1:786759667529:web:9a61a79220a17aedead498',
    messagingSenderId: '786759667529',
    projectId: 'flutter-chat-application-5c200',
    authDomain: 'flutter-chat-application-5c200.firebaseapp.com',
    storageBucket: 'flutter-chat-application-5c200.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5j_hPe9H8uXpvZ7pyJIigQSs05dXK6cs',
    appId: '1:786759667529:android:0cb59bc4ce5d0e10ead498',
    messagingSenderId: '786759667529',
    projectId: 'flutter-chat-application-5c200',
    storageBucket: 'flutter-chat-application-5c200.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApzxm1aWVAKNUd7G8QTMP2ljX4c0JI1tw',
    appId: '1:786759667529:ios:7d7aba9f22d977ecead498',
    messagingSenderId: '786759667529',
    projectId: 'flutter-chat-application-5c200',
    storageBucket: 'flutter-chat-application-5c200.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApzxm1aWVAKNUd7G8QTMP2ljX4c0JI1tw',
    appId: '1:786759667529:ios:7d7aba9f22d977ecead498',
    messagingSenderId: '786759667529',
    projectId: 'flutter-chat-application-5c200',
    storageBucket: 'flutter-chat-application-5c200.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlnWz6sTkKvR0je40n7IC52O0_fCB5XAM',
    appId: '1:786759667529:web:15c437341e669535ead498',
    messagingSenderId: '786759667529',
    projectId: 'flutter-chat-application-5c200',
    authDomain: 'flutter-chat-application-5c200.firebaseapp.com',
    storageBucket: 'flutter-chat-application-5c200.firebasestorage.app',
  );

}